# kubectl create secret generic product-appsettings --from-file=./appsettings.secrets.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-pod
  template:
    metadata:
      labels:
        app: product-pod
    spec:
      containers:
      - name: productapi
        image: acrecommtest.azurecr.io/productservice:v1 #gcr.io/future-depth-264320/productservice:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: product-appsettings
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-pod
  ports:
  - port: 5100
    targetPort: 80
  type: ClusterIP
  #  nodePort: 31002
  #type: NodePort


